require 'app/components/base_component.rb'
require 'app/components/ai.rb'
require 'app/components/combatant.rb'
require 'app/components/consumable.rb'
require 'app/components/healing_consumable.rb'
require 'app/components/inventory.rb'
