require 'tests/app/components/combatant.rb'
require 'tests/app/components/healing.rb'
require 'tests/app/components/lightning_damage.rb'
require 'tests/app/components/inventory.rb'
require 'tests/app/components/ai.rb'
require 'tests/app/components/confusion.rb'
require 'tests/app/components/explosion.rb'
